name: Build

on:
  push:
    branches: [main, stage]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [main, stage, develop]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Clone FoodManager-Frontend repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # - name: Use Node.js 18.x
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: 18.x                                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    #     cache: 'npm'

    # - name: Install npm dependencies
    #   run: npm ci /FoodManager                          # See docs https://docs.npmjs.com/cli/v9/commands/npm-ci

    # - name: Build npm packages
    #   run: npm run build --if-present /FoodManager      # See docs https://docs.npmjs.com/cli/v6/commands/npm-build
